### ISSUE TITLE
read API documentation & create fetch commands for news

### ISSUE THREAD

**Issue by leggeamy** [leggeamy/Daily-Dashboard#2]

**Comment by SterlynKong** [comment]
Crafted a fetch command that should be able to use some parameters to query the Guardian News API and return some data that we should be able to use to fill out our on page news "cards". Will required a little testing.

attached a pic of the response JSON-ized with some annotations.
<img width="777" alt="Screen Shot 2020-10-15 at 10 37 32 PM" src="https://user-images.githubusercontent.com/68391309/96209686-323a4280-0f3e-11eb-90ba-6ae3e6ce9df1.png">

I will next try to iterate through the response to select the objects up to the number of articles / indices we require for the page design.

Any thoughts?

**Comment by SterlynKong** [comment]
Completed code to fetch news based on relevant topics. Small bug regarding allowing user selection still to be fixed.

**Comment by SterlynKong** [comment]
feature/get-news completed as per initial feature discussions
