### ISSUE TITLE
Adjust graph to show hourly weather changes

### ISSUE THREAD

**Issue by SterlynKong** [leggeamy/Daily-Dashboard#21]
Enhancement feedback from "client" - Instructor and TAs

**Comment by leggeamy** [comment]
I have done this and submitted a pull request for it. I don't love how the data labels on the chart look but I can't seem to find a way to change them yet.

**Comment by leggeamy** [comment]
also included in the above mentioned pull request is the update to the news reference footer.

**Comment by SterlynKong** [comment]
Thanks Amy. Approved and merged. I will look over the labels in about a hour to see if I can think of a away to make them more pleasing, as you mentioned. If I think of anything I'll message you on slack.

**Comment by SterlynKong** [comment]
Noticed you changed the weather API. This works but it broke the data validation code that responds on error responses from the API since the error we are looking for may no longer be the same from this new API. Previously, if a city was not found, the search field would be updated with "City not found!". That does not seem to happen now.

**Comment by leggeamy** [comment]
Sorry Sterlyn - the open weather API we were using only offered hourly forecasts for paid subscriptions so I had to find a new one that would offer hourly info for free. I will look into this part of the code today and see if I can get it functioning again.

**Comment by SterlynKong** [comment]
Ah I see. Didn't the openweather API return several items for each day separated into 3 Hr increments? I thought perhaps you could parse those data points for a single day and use them to plot the graph but I may be wrong (I haven't tested this 😅). I lean on your technical knowledge here since you dove the most into this section of the code. I think we just need to check how this new API returns errors and then update our "test" portion of the code so that it works again.
